### ISSUE TITLE
Help with Slingshot functions

### ISSUE THREAD

**Issue by lucygarner** [Morriseylab/scExtras#1]
Hi,

Thank you for generating these functions.  I am particularly interesting in the Slingshot functions, which look like they would be very useful.  However I am struggling to get some of them to work.  

Do you have examples for how to run each of the functions?

I used runSlingshot as follows (sample is my Seurat object):
`test <- runSlingshot(sample, start.clus = 0, reduction = "umap")`

This worked well, but then I tried to run plotCurveHeatmaps and I got an error.  How do I specify the curve in this function?  This is what I tried:
`plotCurveHeatmaps(sample, curve = "curve1")`

The curve is called "curve1" in the SlingshotDataSet object.  However I got the following error:

> Error in UseMethod("arrange_") : 
  no applicable method for 'arrange_' applied to an object of class "NULL"

Could you advise me as to where I am going wrong?

Many thanks,
Lucy

**Comment by mpmorley** [comment]
Section has been re written.
